# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_msgs4/gpsData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class gpsData(genpy.Message):
  _md5sum = "e90aa33e849d86074f13628217060af8"
  _type = "my_msgs4/gpsData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 northVel
float32 skyVel
float32 eastVel
float32 latitude
float32 longtitude
float32 height"""
  __slots__ = ['northVel','skyVel','eastVel','latitude','longtitude','height']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       northVel,skyVel,eastVel,latitude,longtitude,height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gpsData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.northVel is None:
        self.northVel = 0.
      if self.skyVel is None:
        self.skyVel = 0.
      if self.eastVel is None:
        self.eastVel = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longtitude is None:
        self.longtitude = 0.
      if self.height is None:
        self.height = 0.
    else:
      self.northVel = 0.
      self.skyVel = 0.
      self.eastVel = 0.
      self.latitude = 0.
      self.longtitude = 0.
      self.height = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.northVel, _x.skyVel, _x.eastVel, _x.latitude, _x.longtitude, _x.height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.northVel, _x.skyVel, _x.eastVel, _x.latitude, _x.longtitude, _x.height,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.northVel, _x.skyVel, _x.eastVel, _x.latitude, _x.longtitude, _x.height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.northVel, _x.skyVel, _x.eastVel, _x.latitude, _x.longtitude, _x.height,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
